export const AuditAction = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ROLE_CHANGED: 'ROLE_CHANGED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_DEACTIVATED: 'MEMBER_DEACTIVATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  READ: 'READ',
  CLINICAL_READ: 'CLINICAL_READ',
  NOTE_CREATED: 'NOTE_CREATED',
  NOTE_AMENDED: 'NOTE_AMENDED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  EXPORT_REQUESTED: 'EXPORT_REQUESTED',
  EXPORT_COMPLETED: 'EXPORT_COMPLETED',
  DSR_CREATED: 'DSR_CREATED',
  DSR_COMPLETED: 'DSR_COMPLETED',
  DSR_REJECTED: 'DSR_REJECTED',
  SUPPORT_ACCESS_GRANTED: 'SUPPORT_ACCESS_GRANTED',
  SUPPORT_ACCESS_USED: 'SUPPORT_ACCESS_USED',
  TENANT_ANONYMIZED: 'TENANT_ANONYMIZED',
  ANOMALY_TRIGGERED: 'ANOMALY_TRIGGERED',
  SUBSCRIPTION_STATUS_CHANGED: 'SUBSCRIPTION_STATUS_CHANGED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  LOGIN: 'Login',
  LOGIN_FAILED: 'Falha de login',
  LOGOUT: 'Logout',
  PASSWORD_RESET: 'Redefinição de senha',
  ROLE_CHANGED: 'Papel alterado',
  MEMBER_INVITED: 'Membro convidado',
  MEMBER_DEACTIVATED: 'Membro desativado',
  PERMISSION_DENIED: 'Permissão negada',
  REFRESH_REUSE_DETECTED: 'Reuso de refresh',
  READ: 'Leitura clínica',
  CLINICAL_READ: 'Leitura clínica',
  NOTE_CREATED: 'Evolução criada',
  NOTE_AMENDED: 'Evolução retificada',
  MESSAGE_SENT: 'Mensagem enviada',
  REPORT_EXPORTED: 'Relatório exportado',
  EXPORT_REQUESTED: 'Exportação solicitada',
  EXPORT_COMPLETED: 'Exportação concluída',
  DSR_CREATED: 'Solicitação do titular',
  DSR_COMPLETED: 'Solicitação concluída',
  DSR_REJECTED: 'Solicitação recusada',
  SUPPORT_ACCESS_GRANTED: 'Acesso de suporte concedido',
  SUPPORT_ACCESS_USED: 'Acesso de suporte usado',
  TENANT_ANONYMIZED: 'Clínica anonimizada',
  ANOMALY_TRIGGERED: 'Anomalia de leitura',
  SUBSCRIPTION_STATUS_CHANGED: 'Assinatura alterada',
};

export const AUDIT_ACTION_FILTERS: Array<{ value: AuditAction; label: string }> = [
  { value: AuditAction.CLINICAL_READ, label: AUDIT_ACTION_LABELS.CLINICAL_READ },
  { value: AuditAction.NOTE_CREATED, label: AUDIT_ACTION_LABELS.NOTE_CREATED },
  { value: AuditAction.NOTE_AMENDED, label: AUDIT_ACTION_LABELS.NOTE_AMENDED },
  { value: AuditAction.MESSAGE_SENT, label: AUDIT_ACTION_LABELS.MESSAGE_SENT },
  { value: AuditAction.EXPORT_REQUESTED, label: AUDIT_ACTION_LABELS.EXPORT_REQUESTED },
  { value: AuditAction.EXPORT_COMPLETED, label: AUDIT_ACTION_LABELS.EXPORT_COMPLETED },
  { value: AuditAction.DSR_CREATED, label: AUDIT_ACTION_LABELS.DSR_CREATED },
  { value: AuditAction.DSR_COMPLETED, label: AUDIT_ACTION_LABELS.DSR_COMPLETED },
  { value: AuditAction.DSR_REJECTED, label: AUDIT_ACTION_LABELS.DSR_REJECTED },
  { value: AuditAction.SUPPORT_ACCESS_GRANTED, label: AUDIT_ACTION_LABELS.SUPPORT_ACCESS_GRANTED },
  { value: AuditAction.SUPPORT_ACCESS_USED, label: AUDIT_ACTION_LABELS.SUPPORT_ACCESS_USED },
  { value: AuditAction.LOGIN, label: AUDIT_ACTION_LABELS.LOGIN },
  { value: AuditAction.PERMISSION_DENIED, label: AUDIT_ACTION_LABELS.PERMISSION_DENIED },
  { value: AuditAction.REPORT_EXPORTED, label: AUDIT_ACTION_LABELS.REPORT_EXPORTED },
  { value: AuditAction.ANOMALY_TRIGGERED, label: AUDIT_ACTION_LABELS.ANOMALY_TRIGGERED },
];

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action as AuditAction] ?? action;
}
